In [2]:
import pandas as pd
import numpy as np
import quandl
import os

quandl.ApiConfig.api_key = os.getenv('QUANDL_APY_KEY')

In [2]:
df1 = quandl.get_table('SHARADAR/SF1', dimension='MRY', ticker='FB')
df2 = quandl.get_table('SHARADAR/SF2')

/anaconda3/lib/python3.6/site-packages/quandl/get_table.py:38: UserWarning: To request more pages, please set paginate=True in your         quandl.get_table() call. For more information see our documentation:         https://github.com/quandl/quandl-python/blob/master/FOR_ANALYSTS.md#things-to-note
  warnings.warn(Message.WARN_PAGE_LIMIT_EXCEEDED, UserWarning)

In [3]:
pd.options.display.max_rows = 999
pd.set_option('display.max_colwidth', -1)

df_i = quandl.get_table('SHARADAR/INDICATORS')
df_i[df_i['table'] == 'DAILY']

,table,indicator,isfilter,isprimarykey,title,description,unittype
None,,,,,,,
216,DAILY,ticker,Y,Y,Ticker Symbol,"The ticker is a unique identifer for an issuer in the database. Where a ticker contains a ""."" or a ""-"" this is removed from the ticker. For example BRK.B is BRKB. We include the BRK.B ticker in the Related Tickers field. Where a company is delisted and the ticker is recycled; we use that ticker for the currently active company and append a number to the ticker of the delisted company. eg GM is the current actively traded entity; & GM1 is the entity that filed for bankruptcy in 2009.",text
217,DAILY,date,Y,Y,Price Date,"The trade date of the price observations used in determining [MarketCap], [PE], [PS] etc.",date (YYYY-MM-DD)
218,DAILY,lastupdated,Y,N,Last Updated Date,"The last date at which this line item was updated, typically used to filter date to be retrieved for syncing to local records.",date (YYYY-MM-DD)
219,DAILY,ev,N,N,Enterprise Value - Daily,Enterprise value is a measure of the value of a business as a whole; calculated as [MarketCap] plus [DebtUSD] minus [CashnEqUSD].,USD millions
220,DAILY,evebit,N,N,Enterprise Value over EBIT - Daily,Measures the ratio between [EV] and [EBITUSD].,ratio
221,DAILY,evebitda,N,N,Enterprise Value over EBITDA - Daily,Measures the ratio between [EV] and [EBITDAUSD].,USD millions
222,DAILY,marketcap,Y,N,Market Capitalization - Daily,Represents the product of [SharesBas]; [Price] and [ShareFactor].,USD millions
223,DAILY,pb,N,N,Price to Book Value - Daily,Measures the ratio between [MarketCap] and [EquityUSD].,ratio
224,DAILY,pe,N,N,Price Earnings (Damodaran Method) - Daily,Measures the ratio between [MarketCap] and [NetIncCmnUSD].,ratio
225,DAILY,ps,N,N,Price Sales (Damodaran Method) - Daily,Measures the ratio between [MarketCap] and [RevenueUSD].,ratio

In [4]:
df_i[df_i['table'] == 'SF1'].to_csv('sf1_indicators.csv')

In [55]:
df = df1[['calendardate', 'eps', 'revenueusd', 'roic', 'fcf', 'equity']]

In [56]:
df

     calendardate   eps   revenueusd   roic          fcf       equity
None
0      2017-12-31  5.49  40653000000  0.450  17483000000  74347000000
1      2016-12-31  3.56  27638000000  0.443  11617000000  59194000000
2      2015-12-31  1.31  17928000000  0.347   7797000000  44218000000
3      2014-12-31  1.12  12466000000  0.390   5495000000  36096000000
4      2013-12-31  0.62   7872000000  0.236   2860000000  15470000000
5      2012-12-31  0.02   5089000000  0.048    377000000  11755000000
6      2011-12-31  0.52   3711000000  0.617    943000000   4899000000

In [60]:
df['eps_growth'] = df['eps'] / df['eps'].shift(-1) - 1
df['equity_growth'] = df['equity'] / df['equity'].shift(-1) - 1
df['sales_growth'] = df['revenueusd'] / df['revenueusd'].shift(-1) - 1
df['cashflow_growth'] = df['fcf'] / df['fcf'].shift(-1) - 1
df

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

,calendardate,eps,revenueusd,roic,fcf,equity,eps_growth,equity_growth,sales_growth,cashflow_growth
None,,,,,,,,,,
0,2017-12-31,5.49,40653000000,0.450,17483000000,74347000000,0.542135,0.255989,0.470910,0.504950
1,2016-12-31,3.56,27638000000,0.443,11617000000,59194000000,1.717557,0.338686,0.541611,0.489932
2,2015-12-31,1.31,17928000000,0.347,7797000000,44218000000,0.169643,0.225011,0.438152,0.418926
3,2014-12-31,1.12,12466000000,0.390,5495000000,36096000000,0.806452,1.333290,0.583587,0.921329
4,2013-12-31,0.62,7872000000,0.236,2860000000,15470000000,30.000000,0.316036,0.546866,6.586207
5,2012-12-31,0.02,5089000000,0.048,377000000,11755000000,-0.961538,1.399469,0.371328,-0.600212
6,2011-12-31,0.52,3711000000,0.617,943000000,4899000000,NaN,NaN,NaN,NaN

In [28]:
df_t = quandl.get_table('SHARADAR/TICKERS', paginate=True)
df_t['ticker'].count()

34338

In [40]:
df_intrino = pd.read_csv('/Users/carlossouza/Dropbox/Finance/portfolio_simulation/financial_data/data/fb.csv')
df_intrino

,Unnamed: 0,roic,equitygrowth,epsgrowth,revenuegrowth,fcffgrowth,equity,basiceps,totalrevenue,freecashflow
0,2017-12-31,0.501161,0.255989,0.544413,0.470910,1.023670,7.434700e+10,5.49,4.065300e+10,1.274048e+10
1,2016-12-31,0.364564,0.338686,1.705426,0.541611,1.142528,5.919400e+10,3.56,2.763800e+10,6.295727e+09
2,2015-12-31,0.145272,0.225011,0.172727,0.438152,1.166554,4.421800e+10,1.31,1.792800e+10,2.938458e+09
3,2014-12-31,0.201863,1.333290,0.833333,0.583587,-12.643557,3.609600e+10,1.12,1.246600e+10,-1.764270e+10
4,2013-12-31,0.340065,0.316036,59.000000,0.546866,1.549141,1.547000e+10,0.62,7.872000e+09,1.515233e+09
5,2012-12-31,0.018762,1.399469,-0.978261,0.371328,NaN,1.175500e+10,0.02,5.089000e+09,-2.759279e+09
6,2011-12-31,0.621096,NaN,0.642857,0.879939,NaN,4.899000e+09,0.52,3.711000e+09,NaN
7,2010-12-31,NaN,NaN,NaN,NaN,NaN,NaN,0.34,1.974000e+09,NaN