# Evolution of companies meeting Defensive Investor criteria: 2008 to today
**Purpose.** Purpose of this notebook is to evaluate how many companies pass Ben Graham's test criteria for the *defensive investor*, as described in *Chapter 14 of Intelligent Investor*, **over time, from 2008 to today.**

This notebook was built on top of [Stock Selection for the Defensive Investor](http://localhost:8888/notebooks/Stock%20Selection%20for%20the%20Defensive%20Investor%20v2.ipynb#).

In [1]:
%load_ext autoreload
%autoreload 2

import sys
import pandas as pd
import numpy as np
import quandl
import os
import warnings
from datetime import datetime
from tqdm import tqdm_notebook as tqdm
import pandas_datareader as pdr
import matplotlib.pyplot as plt
from graham import *

warnings.filterwarnings('ignore')
quandl.ApiConfig.api_key = os.getenv('QUANDL_APY_KEY')

## Getting necessary data for a given company
This function was changed vs. [Stock Selection for the Defensive Investor](http://localhost:8888/notebooks/Stock%20Selection%20for%20the%20Defensive%20Investor%20v2.ipynb#). Changed from `revenue` to `revenueusd`.

**IMPORTANT: this function is now included at `/graham/defensive.py`.**

In [2]:
get_data('AAPL').head()

,calendardate,datekey,revenueusd,currentratio,eps,dps,bvps,price
236,1997-12-31,1997-12-05,7.081000e+09,1.883,-0.296,0.0,0.340,0.565
237,1998-12-31,1998-12-23,5.941000e+09,2.433,0.084,0.0,0.434,1.422
238,1999-12-31,1999-12-22,6.134000e+09,2.766,0.150,0.0,0.706,3.569
239,2000-12-31,2000-12-14,7.983000e+09,2.808,0.173,0.0,0.897,1.031
240,2001-12-31,2001-12-21,5.363000e+09,3.388,-0.005,0.0,0.798,1.500

## Check if a company pass the 7 criteria
This function was changed vs. [Stock Selection for the Defensive Investor](http://localhost:8888/notebooks/Stock%20Selection%20for%20the%20Defensive%20Investor%20v2.ipynb#). Added the column `first_five_criteria` in the returned Dataframe, which is `True` if a company meets only first five criteria, **excluding PE and PB criteria**. Also added `force_download` flag. Finally, added `relax_current_ratio=False`: if `True`, passes **current_ratio** criteria for companies without it.

**IMPORTANT: this function is now included at `/graham/defensive.py`.**

In [3]:
df_djia = criteria_defensive_investor(get_djia_symbols(), relax_current_ratio=True, dt=datetime(2008, 12, 31))
df_djia

HBox(children=(IntProgress(value=0, max=30), HTML(value='')))

,ticker,last_date,first_date,revenueusd,current_ratio,positive_eps_p10yrs_count,dividend_distribution_p20yrs_count,earnings_change_p10yrs,pe,pb,pexpb,size_criteria,financial_condition_criteria,earnings_stability_criteria,dividend_record_criteria,earnings_growth_criteria,pe_criteria,pb_criteria,first_five_criteria,full_criteria
0,AXP,2007-12-31,1993-12-31,2.773100e+10,NaN,10,15,2.524555,14.012618,4.724527,66.202989,True,True,True,True,True,True,False,True,False
1,AAPL,2008-12-31,1997-12-31,3.247900e+10,2.462,9,0,-5.336478,26.087802,4.356953,113.663329,True,True,False,False,False,False,False,False,False
2,BA,2007-12-31,1997-12-31,6.638700e+10,0.865,10,11,-21.370370,22.143847,7.133406,157.961053,True,False,True,True,False,False,False,False,False
3,CAT,2007-12-31,1997-12-31,4.495800e+10,1.145,10,11,2.271772,14.113681,5.113873,72.175576,True,False,True,True,True,True,False,False,False
4,CSCO,2008-12-31,1995-12-31,3.954000e+10,2.576,9,0,6.414048,19.348703,3.844700,74.389963,True,True,False,False,True,False,False,False,False
5,CVX,2007-12-31,1997-12-31,2.209040e+11,1.165,10,11,3.118712,11.486452,2.398103,27.545700,True,False,True,True,True,True,False,False,False
6,DWDP,2007-12-31,1997-12-31,5.351300e+10,1.499,8,11,1.484185,10.141501,1.952459,19.800868,True,False,False,True,True,True,True,False,False
7,XOM,2007-12-31,1997-12-31,4.045520e+11,1.474,10,11,3.870968,13.542424,3.927238,53.184317,True,False,True,True,True,True,False,False,False
8,GS,2007-12-31,1999-12-31,4.598700e+10,NaN,9,9,NaN,9.968644,1.939438,19.333564,True,True,True,True,False,True,True,False,False
9,HD,2007-12-31,1996-12-31,7.734900e+10,1.155,10,12,5.487340,11.082174,2.748049,30.454353,True,False,True,True,True,True,False,False,False
10,IBM,2007-12-31,1997-12-31,9.878600e+10,1.200,10,11,1.993528,18.568182,5.561066,103.258880,True,False,True,True,True,False,False,False,False
11,INTC,2007-12-31,1997-12-31,3.833400e+10,2.787,10,11,1.094387,17.518625,2.783393,48.761209,True,True,True,True,False,False,False,False,False
12,JNJ,2007-12-31,2001-12-31,6.109500e+10,1.510,7,7,NaN,17.489478,4.166612,72.871874,True,False,True,True,False,False,False,False,False
13,KO,2007-12-31,1997-12-31,2.885700e+10,0.915,10,11,1.355289,26.270987,6.333617,166.390378,True,False,True,True,True,False,False,False,False
14,JPM,2007-12-31,1997-12-31,7.137200e+10,NaN,10,11,1.337188,10.986486,1.120514,12.310510,True,True,True,True,True,True,True,True,True
15,MCD,2007-12-31,1997-12-31,2.278660e+10,0.796,10,11,1.971631,24.194245,4.304916,104.154179,True,False,True,True,True,False,False,False,False
16,MMM,2007-12-31,1995-12-31,2.446200e+10,1.835,10,13,2.705671,15.958084,4.839881,77.235232,True,False,True,True,True,False,False,False,False
17,MRK,2007-12-31,1997-12-31,2.419770e+10,1.227,10,11,0.985205,23.957597,5.382234,128.945391,True,False,True,True,False,False,False,False,False
18,MSFT,2008-12-31,1994-12-31,6.042000e+10,1.447,10,6,4.545455,16.958242,6.567926,111.380485,True,False,True,False,True,False,False,False,False
19,NKE,2008-12-31,1998-12-31,1.862700e+10,2.661,10,11,4.575581,18.182973,3.587365,65.228967,True,True,True,True,True,False,False,True,False
20,PFE,2007-12-31,1997-12-31,4.841800e+10,2.146,10,11,2.810903,13.503030,2.322285,31.357882,True,True,True,True,True,True,False,True,False
21,PG,2008-12-31,1998-12-31,8.350300e+10,0.792,10,11,2.401460,21.583587,3.100467,66.919202,True,False,True,True,True,False,False,False,False
22,TRV,2007-12-31,1997-12-31,2.601700e+10,NaN,9,11,1.252013,9.079100,1.121170,10.179216,True,True,False,True,False,True,True,False,False
23,UNH,2007-12-31,1997-12-31,7.543100e+10,0.841,9,10,10.743322,15.502703,3.032995,47.019619,True,False,False,False,True,False,False,False,False
24,UTX,2007-12-31,1997-12-31,5.475900e+10,1.263,10,11,3.390390,18.991143,3.284920,62.384380,True,False,True,True,True,False,False,False,False
25,VZ,2007-12-31,1998-12-31,9.346900e+10,0.756,10,10,NaN,16.622951,2.121420,35.264254,True,False,True,True,False,False,False,False,False
26,V,2008-12-31,2007-12-31,6.263000e+09,1.560,1,1,NaN,48.312500,1.673885,80.869559,True,False,False,False,False,False,False,False,False
27,WBA,2008-12-31,1998-12-31,5.903400e+10,1.570,10,11,3.851133,12.705882,1.938163,24.626076,True,False,True,True,True,True,False,False,False
28,WMT,2007-12-31,1994-12-31,3.787990e+11,0.814,10,14,4.176471,18.549296,3.251651,60.315839,True,False,True,True,True,False,False,False,False
29,DIS,2008-12-31,1993-12-31,3.784300e+10,1.006,9,14,2.468203,9.048309,1.084728,9.814955,True,False,False,False,True,True,True,False,False

In [4]:
df_djia = analysis(df_djia)

print('\nCompanies passing first 5 criteria: ' + str(df_djia[(df_djia['first_five_criteria'] == True)]['ticker'].tolist()))
print('Companies passing all criteria: '+ str(df_djia[(df_djia['full_criteria'] == True)]['ticker'].tolist()))

  30 companies passing size criteria of minimum $100 million revenues
   9 companies passing financial condition criteria of minimum 2 current ratio
  23 companies passing earnings stability criteria of positive earnings in past 10 years
  24 companies passing dividend record criteria of uninterrupted payments in past 20 years
  21 companies passing earnings growth criteria of minimum 33% growth in past 10 years
  12 companies passing moderate PE ratio criteria of maximum 15
   5 companies passing moderate PB ratio criteria of maximum 1.5, or PE * PB of maximum 22.5
   4 companies passing all except moderate PE and PB ratio criteria
   1 companies passing all criteria

Companies passing first 5 criteria: ['AXP', 'JPM', 'NKE', 'PFE']
Companies passing all criteria: ['JPM']

In [5]:
summary_columns = ['ticker', 'current_ratio', 
                       'positive_eps_p10yrs_count', 'dividend_distribution_p20yrs_count', 
                       'earnings_change_p10yrs', 'pe', 'pb', 'pexpb', 'count_successful_criteria', 
                   'count_successful_criteria_except_pepb']

df_djia[df_djia['count_successful_criteria_except_pepb'] == 5].sort_values(['count_successful_criteria_except_pepb', 'count_successful_criteria'], 
                    ascending=False)[summary_columns]
#[['ticker', 'count_successful_criteria']]

,ticker,current_ratio,positive_eps_p10yrs_count,dividend_distribution_p20yrs_count,earnings_change_p10yrs,pe,pb,pexpb,count_successful_criteria,count_successful_criteria_except_pepb
14,JPM,NaN,10,11,1.337188,10.986486,1.120514,12.310510,7,5
0,AXP,NaN,10,15,2.524555,14.012618,4.724527,66.202989,6,5
20,PFE,2.146,10,11,2.810903,13.503030,2.322285,31.357882,6,5
19,NKE,2.661,10,11,4.575581,18.182973,3.587365,65.228967,5,5

## Return list of DJIA companies passing criteria over time

In [7]:
dr = pd.date_range('2008-01-01', '2019-01-01', freq='Y')

list_djia = get_djia_symbols()
fname = os.path.join(os.getcwd(), 'data_defensive', 'sf1.csv')
df_all = pd.read_csv(fname, parse_dates=['calendardate', 'datekey'])

for date in dr:
    ls = criteria_defensive_investor_list(list_djia, all_data=df_all, relax_current_ratio=False, 
                                          dt=date, show_progress=False)
    print(f"{date:%Y-%m-%d} companies: {ls}")

2008-12-31 companies: ['NKE', 'PFE']
2009-12-31 companies: ['NKE']
2010-12-31 companies: ['MMM', 'NKE']
2011-12-31 companies: ['MMM', 'NKE', 'PFE']
2012-12-31 companies: ['INTC', 'JNJ', 'MMM', 'NKE']
2013-12-31 companies: ['DWDP', 'INTC', 'MMM', 'NKE']
2014-12-31 companies: ['DWDP', 'INTC', 'JNJ', 'NKE', 'PFE', 'VZ']
2015-12-31 companies: ['DWDP', 'JNJ', 'NKE', 'PFE']
2016-12-31 companies: ['DWDP', 'INTC', 'JNJ', 'MCD', 'NKE']
2017-12-31 companies: ['JNJ', 'NKE']
2018-12-31 companies: ['NKE']

## Return list of S&P 500 companies passing criteria over time (and save in a Dictionary)

In [8]:
from collections import defaultdict

dic = defaultdict(list)
dr = pd.date_range('2008-01-01', '2019-01-01', freq='Y')
list_sp500 = get_sp500_symbols()

fname = os.path.join(os.getcwd(), 'data_defensive', 'sf1.csv')
df_all = pd.read_csv(fname, parse_dates=['calendardate', 'datekey'])

for date in dr:
    list_passing_companies = criteria_defensive_investor_list(list_sp500, all_data=df_all, 
                                                              relax_current_ratio=False, 
                                                              dt=date, show_progress=False)
    print(f"{date:%Y-%m-%d} companies: {list_passing_companies}")
    dic[date] = list_passing_companies

2008-12-31 companies: ['ALB', 'BDX', 'CTAS', 'XRAY', 'BEN', 'GWW', 'HRS', 'HP', 'ITW', 'LB', 'MDT', 'NKE', 'NUE', 'PFE', 'SYK', 'TIF', 'TSS']
2009-12-31 companies: ['ALB', 'BDX', 'CTAS', 'CAG', 'XRAY', 'EXPD', 'FAST', 'BEN', 'GWW', 'HOG', 'HRL', 'IFF', 'MDT', 'NKE', 'NUE', 'PNR', 'ROK', 'SNA', 'SYK', 'TIF', 'TSS']
2010-12-31 companies: ['MMM', 'ALB', 'BDX', 'BMY', 'CTAS', 'XRAY', 'EXPD', 'FAST', 'BEN', 'GWW', 'HP', 'ITW', 'IFF', 'MLM', 'NKE', 'PNR', 'ROK', 'SNA', 'SYK', 'TFX', 'TIF', 'TSS']
2011-12-31 companies: ['MMM', 'ALB', 'ADM', 'BDX', 'CTAS', 'XRAY', 'EXPD', 'FAST', 'BEN', 'GWW', 'HP', 'HRL', 'IFF', 'NKE', 'PFE', 'SNA', 'SYK', 'TFX', 'TIF', 'TSS']
2012-12-31 companies: ['MMM', 'ALB', 'AOS', 'BDX', 'CTAS', 'EXPD', 'FAST', 'GPS', 'HP', 'HRL', 'ITW', 'INTC', 'IFF', 'JNJ', 'NKE', 'JWN', 'ROK', 'ROP', 'SNA', 'SYK', 'TFX', 'TIF']
2013-12-31 companies: ['MMM', 'ABT', 'ALB', 'AOS', 'BDX', 'CTAS', 'DWDP', 'EL', 'EXPD', 'FAST', 'GWW', 'HP', 'HFC', 'HRL', 'ITW', 'INTC', 'IFF', 'MAT', 'MDT', 'MCO', 'NKE', 'JWN', 'PCAR', 'ROK', 'SNA', 'SYK', 'TXN', 'TIF', 'TSS']
2014-12-31 companies: ['ABT', 'ALB', 'AOS', 'BDX', 'CTAS', 'CMI', 'DHR', 'DOV', 'DWDP', 'EL', 'EXPD', 'FAST', 'GWW', 'HP', 'HFC', 'HRL', 'INTC', 'IFF', 'JNJ', 'MAT', 'MDT', 'MCO', 'NKE', 'JWN', 'PFE', 'ROK', 'ROP', 'SNA', 'SYK', 'TXN', 'TIF', 'TSS', 'VFC', 'VZ']
2015-12-31 companies: ['ALB', 'AOS', 'CTAS', 'CMI', 'DWDP', 'EL', 'EXPD', 'FAST', 'GWW', 'HAS', 'HP', 'HFC', 'ITW', 'IFF', 'SJM', 'JNJ', 'MAT', 'MDT', 'MCO', 'NKE', 'PH', 'PFE', 'PVH', 'ROK', 'ROP', 'SNA', 'SYK', 'TXN', 'TIF', 'TSS', 'VFC']
2016-12-31 companies: ['AOS', 'BAX', 'CMI', 'XRAY', 'DWDP', 'EXPD', 'FAST', 'HAS', 'ITW', 'INTC', 'JNJ', 'LB', 'MCD', 'MDT', 'MCO', 'NKE', 'PCAR', 'PH', 'ROK', 'ROP', 'SNA', 'SYK', 'TXN', 'TIF', 'TSS', 'VFC']
2017-12-31 companies: ['APD', 'ALB', 'AME', 'AOS', 'BAX', 'BDX', 'XRAY', 'EXPD', 'FAST', 'ITW', 'JNJ', 'NKE', 'SYK', 'TXN', 'TIF', 'TSS', 'VFC']
2018-12-31 companies: ['APD', 'ALB', 'AOS', 'BAX', 'CTAS', 'COO', 'EXPD', 'FAST', 'GWW', 'HAS', 'ITW', 'IFF', 'MLM', 'NKE', 'SYK', 'TXN', 'TIF']

In [9]:
dic[datetime(2018, 12, 31)]

['APD',
 'ALB',
 'AOS',
 'BAX',
 'CTAS',
 'COO',
 'EXPD',
 'FAST',
 'GWW',
 'HAS',
 'ITW',
 'IFF',
 'MLM',
 'NKE',
 'SYK',
 'TXN',
 'TIF']

## Return list of ALL companies passing criteria over time (and save in a Dictionary)

In [10]:
dr = pd.date_range('2008-01-01', '2019-01-01', freq='Y')
list_all = get_sf1_symbols()
dic2 = defaultdict(list)

fname = os.path.join(os.getcwd(), 'data_defensive', 'sf1.csv')
df_all = pd.read_csv(fname, parse_dates=['calendardate', 'datekey'])

for date in dr:
    list_passing_companies = criteria_defensive_investor_list(list_all, all_data=df_all, 
                                                              relax_current_ratio=False, 
                                                              dt=date, show_progress=True)
    print(f"{date:%Y-%m-%d} companies: {list_passing_companies}")
    dic2[date] = list_passing_companies

HBox(children=(IntProgress(value=0, max=14121), HTML(value='')))

2008-12-31 companies: ['ABI1', 'ACET', 'AIT', 'ALB', 'AMN1', 'AMWD', 'ASH', 'BDX', 'BEN', 'BEZ', 'BMS', 'BRC', 'CRR', 'CSL', 'CTAS', 'CUB', 'EBF', 'EML', 'ESV', 'ETH', 'EV', 'FELE', 'FICO', 'FRED', 'FUL', 'GK', 'GRC', 'GWW', 'HEI', 'HP', 'HRS', 'IEX', 'ITW', 'LB', 'LCUT', 'LECO', 'MDT', 'MOV', 'MSA', 'NKE', 'NUE', 'PFE', 'PLL1', 'RAVN', 'RBC', 'RS', 'SCCO', 'SCHN', 'SEB', 'SEIC', 'SNHY', 'SYK', 'THO', 'TIF', 'TNC', 'TSS', 'UFPI', 'VMI', 'WEYS', 'WGO', 'WSO', 'WWD', 'XRAY']

HBox(children=(IntProgress(value=0, max=14121), HTML(value='')))

2009-12-31 companies: ['ABI1', 'ACET', 'AIT', 'ALB', 'AMN1', 'ATR', 'B', 'BCPC', 'BCR', 'BDX', 'BEN', 'BEZ', 'BMS', 'BRC', 'CAG', 'CATO', 'CMC', 'CRR', 'CSL', 'CTAS', 'CUB', 'DCI', 'EML', 'ESV', 'EV', 'EXP', 'EXPD', 'FAST', 'FELE', 'FICO', 'FRD', 'FRED', 'FUL', 'GGG', 'GRC', 'GWW', 'HEI', 'HOG', 'HRL', 'HUBB', 'HWKN', 'IEX', 'IFF', 'LECO', 'LNN', 'MATW', 'MDT', 'MOV', 'MSA', 'NKE', 'NTP', 'NUE', 'PLL1', 'PNR', 'RAVN', 'ROK', 'RS', 'RYN', 'SCCO', 'SEB', 'SEIC', 'SKYW', 'SNA', 'SNHY', 'SYK', 'TDW', 'THO', 'TIF', 'TSS', 'UFPI', 'VMI', 'WEYS', 'WSO', 'WWD', 'XRAY']

HBox(children=(IntProgress(value=0, max=14121), HTML(value='')))

2010-12-31 companies: ['ABI1', 'AIT', 'ALB', 'ALG', 'AMN1', 'ATR', 'B', 'BCPC', 'BCR', 'BDX', 'BEN', 'BEZ', 'BF.B', 'BMI', 'BMS', 'BMY', 'BRC', 'CAJ', 'CATO', 'CRR', 'CSL', 'CTAS', 'CUB', 'DCI', 'ESV', 'EXPD', 'FAST', 'FICO', 'FRED', 'FUL', 'GR', 'GRC', 'GWW', 'HEI', 'HP', 'HUBB', 'HWKN', 'IEX', 'IFF', 'ITW', 'KMG', 'LECO', 'LNN', 'MATW', 'MLM', 'MMM', 'MSA', 'NAT', 'NKE', 'PLL1', 'PNR', 'RAVN', 'RBC', 'ROK', 'RS', 'RYN', 'SCCO', 'SCL', 'SEB', 'SEIC', 'SKYW', 'SNA', 'SYK', 'TDW', 'TFX', 'THO', 'TIF', 'TSS', 'VMI', 'WEYS', 'WSO', 'WWD', 'XRAY']

HBox(children=(IntProgress(value=0, max=14121), HTML(value='')))

2011-12-31 companies: ['ABI1', 'ADM', 'AIT', 'ALB', 'ALG', 'AMN1', 'ATR', 'BCPC', 'BCR', 'BDX', 'BEAM', 'BEC', 'BEN', 'BEZ', 'BF.B', 'BMI', 'BMS', 'BRC', 'CAJ', 'CATO', 'CRR', 'CTAS', 'CW', 'DCI', 'ESV', 'EXPD', 'FAST', 'FELE', 'FICO', 'FRD', 'FRED', 'FUL', 'GGG', 'GR', 'GRC', 'GWW', 'HEI', 'HP', 'HRL', 'HUBB', 'HWKN', 'IFF', 'KMG', 'LANC', 'LECO', 'LLTC', 'LNN', 'MATW', 'MMM', 'MSA', 'NKE', 'OMI', 'PFE', 'PLL1', 'RAVN', 'RBC', 'RS', 'RYN', 'SCCO', 'SCL', 'SEB', 'SEIC', 'SKYW', 'SNA', 'SNHY', 'SXT', 'SYK', 'TDW', 'TFX', 'THO', 'TIF', 'TSS', 'UNF', 'UVV', 'VMI', 'WDFC', 'WEYS', 'WSO', 'WWD', 'XRAY']

HBox(children=(IntProgress(value=0, max=14121), HTML(value='')))

2012-12-31 companies: ['ABI1', 'ACET', 'ACO', 'AIT', 'ALB', 'ALG', 'AMN1', 'AOS', 'APAGF', 'ATR', 'BCPC', 'BDX', 'BEAM', 'BEC', 'BEZ', 'BF.B', 'BHI', 'BMI', 'BMS', 'CAJ', 'CATO', 'CLC', 'CRR', 'CTAS', 'CUB', 'CW', 'DCI', 'EQT', 'EXPD', 'FAST', 'FELE', 'FRD', 'FRED', 'FUL', 'GGG', 'GPS', 'GR', 'GRC', 'HEI', 'HP', 'HRL', 'HUBB', 'HWKN', 'IEX', 'IFF', 'INTC', 'ITW', 'JCS', 'JNJ', 'JWN', 'KDN', 'KMG', 'KWR', 'LANC', 'LECO', 'LLTC', 'LNN', 'LUFK', 'MATW', 'MMM', 'MSA', 'NKE', 'ODC', 'OMI', 'PLL1', 'RAVN', 'RBC', 'ROK', 'ROP', 'RS', 'RSH', 'SCCO', 'SCL', 'SEIC', 'SIAL', 'SJW', 'SNA', 'SNHY', 'SXT', 'SYK', 'TDW', 'TFX', 'THO', 'TIF', 'UNF', 'VIVO', 'VMI', 'WMK', 'WSO', 'WWD']

HBox(children=(IntProgress(value=0, max=14121), HTML(value='')))

2013-12-31 companies: ['ABI1', 'ABT', 'ACET', 'ACO', 'AIT', 'ALB', 'ALG', 'AMN1', 'AOS', 'APAGF', 'ATR', 'B', 'BCPC', 'BCR', 'BDX', 'BEAM', 'BEC', 'BEZ', 'BF.B', 'BHI', 'CAJ', 'CATO', 'CCF', 'CCJ', 'CLC', 'CRR', 'CSH', 'CSL', 'CTAS', 'CUB', 'DCI', 'DWDP', 'EL', 'EXPD', 'FAST', 'FELE', 'FRD', 'FRED', 'FUL', 'GG', 'GGG', 'GR', 'GRC', 'GWW', 'HEI', 'HFC', 'HP', 'HRL', 'HUBB', 'HWKN', 'IEX', 'IFF', 'INTC', 'ITW', 'JCS', 'JWN', 'KDN', 'KMG', 'KWR', 'LANC', 'LECO', 'LNN', 'LUFK', 'MAT', 'MATW', 'MCO', 'MDT', 'MGEE', 'MMM', 'MSA', 'NKE', 'ODC', 'PCAR', 'PLL1', 'PLPC', 'RAVN', 'RBC', 'ROK', 'RS', 'SCCO', 'SCL', 'SEIC', 'SIAL', 'SNA', 'SNHY', 'STRA', 'SXT', 'SYK', 'THO', 'TIF', 'TSS', 'TWIN', 'TXN', 'UNF', 'VIVO', 'VMI', 'WEYS', 'WMK', 'WSO', 'WST', 'WTS', 'WWD', 'WWW']

HBox(children=(IntProgress(value=0, max=14121), HTML(value='')))

2014-12-31 companies: ['ABI1', 'ABT', 'ACET', 'ACO', 'AIT', 'ALB', 'ALG', 'AMN1', 'AOS', 'ASH', 'ATR', 'BCPC', 'BCR', 'BDX', 'BEC', 'BEZ', 'BF.B', 'BHI', 'CATO', 'CCF', 'CCJ', 'CLC', 'CMI', 'CMP', 'CRR', 'CSH', 'CSL', 'CTAS', 'CUB', 'CW', 'DCI', 'DCMYY', 'DHR', 'DOV', 'DWDP', 'EL', 'EML', 'EQT', 'EXP', 'EXPD', 'FAST', 'FELE', 'FRD', 'FUL', 'GGB', 'GGG', 'GR', 'GRC', 'GWW', 'HEI', 'HFC', 'HP', 'HRL', 'HUBB', 'HWKN', 'IEX', 'IFF', 'INTC', 'JNJ', 'JWN', 'KDN', 'KWR', 'LECO', 'LLTC', 'LNN', 'LUFK', 'MAT', 'MCO', 'MDT', 'MSA', 'NJDCY', 'NKE', 'ODC', 'PFE', 'PLPC', 'RAVN', 'RBC', 'ROK', 'ROP', 'RS', 'SCCO', 'SCL', 'SEIC', 'SIAL', 'SNA', 'SNHY', 'SXT', 'SYK', 'TDW', 'THO', 'TIF', 'TSS', 'TTC', 'TWIN', 'TXN', 'UNF', 'VFC', 'VIVO', 'VMI', 'VZ', 'WAB', 'WERN', 'WEYS', 'WMK', 'WSO', 'WST', 'WTS', 'WWD', 'WWW']

HBox(children=(IntProgress(value=0, max=14121), HTML(value='')))

2015-12-31 companies: ['ABI1', 'ACET', 'ACO', 'AIT', 'ALB', 'ALG', 'AMN1', 'AOS', 'ATR', 'AWR', 'B', 'BCR', 'BEC', 'BEZ', 'BF.B', 'BHI', 'CATO', 'CCF', 'CLC', 'CMI', 'CMP', 'CNL', 'CRR', 'CRS', 'CSH', 'CSL', 'CTAS', 'CW', 'DWDP', 'EL', 'EML', 'ERJ', 'EXPD', 'FAST', 'FELE', 'FUL', 'GGB', 'GGG', 'GR', 'GRC', 'GWW', 'HAS', 'HEI', 'HFC', 'HP', 'HUBB', 'HWKN', 'IEX', 'IFF', 'ITW', 'JNJ', 'KDN', 'KEQU', 'KWR', 'LECO', 'LLTC', 'LNCE', 'LNN', 'LUFK', 'MAT', 'MCO', 'MDT', 'MGEE', 'MON', 'MSA', 'NJDCY', 'NKE', 'ODC', 'PCP', 'PFE', 'PH', 'PLPC', 'PVH', 'RAVN', 'RBC', 'ROK', 'ROP', 'RS', 'SCCO', 'SCL', 'SEIC', 'SGC', 'SIAL', 'SJM', 'SNA', 'SNHY', 'SYK', 'THO', 'TIF', 'TSS', 'TWIN', 'TXN', 'UNF', 'VFC', 'VIVO', 'VMI', 'WAB', 'WDFC', 'WERN', 'WSO', 'WST', 'WWD', 'WWW']

HBox(children=(IntProgress(value=0, max=14121), HTML(value='')))

2016-12-31 companies: ['ABI1', 'ACET', 'ACO', 'AIT', 'ALG', 'AMN1', 'AOS', 'B', 'BAX', 'BCPC', 'BEC', 'BEZ', 'BF.B', 'CALM', 'CATO', 'CCF', 'CLC', 'CMI', 'CMP', 'CNL', 'CSH', 'CSL', 'CW', 'DWDP', 'EML', 'EXP', 'EXPD', 'FAST', 'FELE', 'FUL', 'GGG', 'GR', 'GRC', 'HAS', 'HEI', 'HUBB', 'HWKN', 'IEX', 'INTC', 'ITRN', 'ITW', 'JNJ', 'KAMN', 'KDN', 'KEQU', 'KWR', 'LANC', 'LB', 'LECO', 'LLTC', 'LNCE', 'LNN', 'LUFK', 'MCD', 'MCO', 'MDT', 'MGEE', 'NKE', 'ODC', 'PCAR', 'PCP', 'PH', 'PLPC', 'RAVN', 'RBC', 'ROK', 'ROP', 'RPM', 'RS', 'SCCO', 'SCL', 'SEIC', 'SGC', 'SIAL', 'SNA', 'SNHY', 'SXT', 'SYK', 'TIF', 'TSS', 'TXN', 'UGP', 'UNF', 'UVV', 'VFC', 'VGR', 'VIVO', 'VMI', 'VSEC', 'WAB', 'WDFC', 'WSO', 'WST', 'WWW', 'XRAY']

HBox(children=(IntProgress(value=0, max=14121), HTML(value='')))

2017-12-31 companies: ['ABI1', 'ACET', 'ACO', 'AIT', 'ALB', 'ALG', 'AME', 'AMN1', 'AOS', 'APD', 'B', 'BAX', 'BCR', 'BDX', 'BEC', 'BEZ', 'BF.B', 'BMS', 'CATO', 'CCF', 'CLC', 'CNL', 'CSH', 'CSL', 'CW', 'DCI', 'EXPD', 'FAST', 'FELE', 'GGG', 'GR', 'GRC', 'HEI', 'HUBB', 'HWKN', 'IEX', 'ITRN', 'ITW', 'JNJ', 'KDN', 'KEQU', 'KWR', 'LANC', 'LECO', 'LLTC', 'LNCE', 'LNN', 'LUFK', 'NKE', 'ODC', 'PCP', 'SCL', 'SEIC', 'SGC', 'SIAL', 'SNHY', 'SWM', 'SXT', 'SYK', 'TIF', 'TSS', 'TXN', 'UGP', 'UNF', 'UVV', 'VFC', 'VIVO', 'VMI', 'WDFC', 'WSO', 'WST', 'WWD', 'WWW', 'XRAY']

HBox(children=(IntProgress(value=0, max=14121), HTML(value='')))

2018-12-31 companies: ['ABI1', 'ACO', 'AIT', 'ALB', 'ALG', 'AMN1', 'AOS', 'APD', 'ATR', 'BAX', 'BCR', 'BEC', 'BEZ', 'BF.B', 'CCF', 'CLC', 'CMP', 'CNL', 'COO', 'CSH', 'CSL', 'CTAS', 'CW', 'DCI', 'EXP', 'EXPD', 'FAST', 'FELE', 'GGG', 'GR', 'GRC', 'GWW', 'HAS', 'HEI', 'HUBB', 'IDA', 'IEX', 'IFF', 'INGR', 'ITW', 'KAMN', 'KDN', 'KEQU', 'KWR', 'LANC', 'LECO', 'LLTC', 'LUFK', 'MLM', 'NKE', 'ODC', 'PCP', 'RPM', 'SCL', 'SEIC', 'SGC', 'SIAL', 'SNHY', 'SNN', 'SWM', 'SXT', 'SYK', 'TIF', 'TXN', 'UFPI', 'UGP', 'UNF', 'UVV', 'VMI', 'VSEC', 'WDR', 'WSO', 'WST']

In [19]:
for key, value in dic.items():
    print(f'{key:%Y-%m-%d}: {len(value)} companies pass criteria')

2008-12-31: 63 companies pass criteria
2009-12-31: 75 companies pass criteria
2010-12-31: 73 companies pass criteria
2011-12-31: 80 companies pass criteria
2012-12-31: 90 companies pass criteria
2013-12-31: 103 companies pass criteria
2014-12-31: 109 companies pass criteria
2015-12-31: 103 companies pass criteria
2016-12-31: 95 companies pass criteria
2017-12-31: 74 companies pass criteria
2018-12-31: 73 companies pass criteria

In [23]:
dr2 = pd.date_range('2009-01-01', '2010-01-01', freq='M')
dic3 = defaultdict(list)

for date in dr2:
    list_passing_companies = criteria_defensive_investor_list(list_all, all_data=df_all, 
                                                              relax_current_ratio=False, 
                                                              dt=date, show_progress=True)
    print(f"{date:%Y-%m-%d}: {len(list_passing_companies)} companies pass criteria")
    dic3[date] = list_passing_companies

KeyboardInterrupt: